apps/system/urls.py
from django.urls import path

from .views import SystemView
from . import views_structure, views_user, views_menu, views_role

app_name = 'system'

urlpatterns = [
    path('', SystemView.as_view(), name='login'),
    path('basic/structure/', views_structure.StructureView.as_view(), name='basic-structure'),
    path('basic/structure/create/', views_structure.StructureCreateView.as_view(), name='basic-structure-create'),
    path('basic/structure/list/', views_structure.StructureListView.as_view(), name='basic-structure-list'),
    path('basic/structure/delete/', views_structure.StructureDeleteView.as_view(), name='basic-structure-delete'),
    path('basic/structure/add_user/', views_structure.Structure2UserView.as_view(), name='basic-structure-add_user'),

    path('basic/user/', views_user.UserView.as_view(), name='basic-user'),
    path('basic/user/list/', views_user.UserListView.as_view(), name='basic-user-list'),
    path('basic/user/create/', views_user.UserCreateView.as_view(), name='basic-user-create'),
    path('basic/user/detail/', views_user.UserDetailView.as_view(), name='basic-user-detail'),
    path('basic/user/update/', views_user.UserUpdateView.as_view(), name='basic-user-update'),
    path('basic/user/password_change/', views_user.PasswordChangeView.as_view(), name='basic-user-password_change'),
    path('basic/user/delete/', views_user.UserDeleteView.as_view(), name='basic-user-delete'),
    path('basic/user/enable/', views_user.UserEnableView.as_view(), name='basic-user-enable'),
    path('basic/user/disable/', views_user.UserDisableView.as_view(), name='basic-user-disable'),

    path('rbac/menu/', views_menu.MenuListView.as_view(), name='rbac-menu'),
    path('rbac/menu/create/', views_menu.MenuCreateView.as_view(), name='rbac-menu-create'),
    path('rbac/menu/update/', views_menu.MenuUpdateView.as_view(), name='rbac-menu-update'),

    path('rbac/role/', views_role.RoleView.as_view(), name='rbac-role'),
    path('rbac/role/create/', views_role.RoleCreateView.as_view(), name='rbac-role-create'),
    path('rbac/role/list/', views_role.RoleListView.as_view(), name='rbac-role-list'),
    path('rbac/role/update/', views_role.RoleUpdateView.as_view(), name='rbac-role-update'),
    path('rbac/role/delete/', views_role.RoleDeleteView.as_view(), name='rbac-role-delete'),
    path('rbac/role/role2user/', views_role.Role2UserView.as_view(), name="rbac-role-role2user"),
    path('rbac/role/role2menu/', views_role.Role2MenuView.as_view(), name="rbac-role-role2menu"),
    path('rbac/role/role2menu_list/', views_role.Role2MenuListView.as_view(), name="rbac-role-role2menu_list"),
]

sandboxMP/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.urls import re_path
from django.views.static import serve

from system.views_user import IndexView, LoginView, LogoutView
from cmdb.tests import TestLoggingView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('system/', include('system.urls', namespace='system')),
    path('cmdb/', include('cmdb.urls', namespace='cmdb')),

    path('test/', TestLoggingView.as_view()),

]

if settings.DEBUG:
    urlpatterns += [
        re_path(r'^media/(?P<path>.*)$', serve, {"document_root": settings.MEDIA_ROOT}),

    ]

apps/system/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class Menu(models.Model):
    """
    菜单
    """
    name = models.CharField(max_length=30, unique=True, verbose_name="菜单名")  # unique=True, 这个字段在表中必须有唯一值.
    parent = models.ForeignKey("self", null=True, blank=True, on_delete=models.SET_NULL, verbose_name="父菜单")
    icon = models.CharField(max_length=50, null=True, blank=True, verbose_name="图标")
    code = models.CharField(max_length=50, null=True, blank=True, verbose_name="编码")
    url = models.CharField(max_length=128, unique=True, null=True, blank=True)
    number = models.FloatField(null=True, blank=True, verbose_name="编号")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '菜单'
        verbose_name_plural = verbose_name
        ordering = ['number']

    @classmethod
    def get_menu_by_request_url(cls, url):
        try:
            return dict(menu=Menu.objects.get(url=url))
        except:
            None


class Role(models.Model):
    """
    角色：用于权限绑定
    """
    name = models.CharField(max_length=32, unique=True, verbose_name="角色")
    permissions = models.ManyToManyField("menu", blank=True, verbose_name="URL授权")
    desc = models.CharField(max_length=50, blank=True, null=True, verbose_name="描述")


class Structure(models.Model):
    """
    组织架构
    """
    type_choices = (("unit", "单位"), ("department", "部门"))
    name = models.CharField(max_length=60, verbose_name="名称")
    type = models.CharField(max_length=20, choices=type_choices, default="department", verbose_name="类型")
    parent = models.ForeignKey("self", null=True, blank=True, on_delete=models.SET_NULL, verbose_name="父类架构")

    class Meta:
        verbose_name = "组织架构"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class UserProfile(AbstractUser):
    name = models.CharField(max_length=20, default="", verbose_name="姓名")
    birthday = models.DateField(null=True, blank=True, verbose_name="出生日期")
    gender = models.CharField(max_length=10, choices=(("male", "男"), ("female", "女")),
                              default="male", verbose_name="性别")
    mobile = models.CharField(max_length=11, default="", verbose_name="手机号码")
    email = models.EmailField(max_length=50, verbose_name="邮箱")
    image = models.ImageField(upload_to="image/%Y/%m", default="image/default.jpg",
                              max_length=100, null=True, blank=True)
    department = models.ForeignKey("Structure", null=True, blank=True, on_delete=models.SET_NULL, verbose_name="部门")
    post = models.CharField(max_length=50, null=True, blank=True, verbose_name="职位")
    superior = models.ForeignKey("self", null=True, blank=True, on_delete=models.SET_NULL, verbose_name="上级主管")
    roles = models.ManyToManyField("role", verbose_name="角色", blank=True)

    class Meta:
        verbose_name = "用户信息"
        verbose_name_plural = verbose_name
        ordering = ['id']

    def __str__(self):
        return self.name

apps/system/forms.py
# @Time   : 2018/10/17 23:13
# @Author : RobbieHan
# @File   : forms.py

import re
from django import forms
from django.contrib.auth import get_user_model

from .models import Structure, Menu

User = get_user_model()


class LoginForm(forms.Form):
    username = forms.CharField(required=True, error_messages={"requeired": "请填写用户名"})
    password = forms.CharField(required=True, error_messages={"requeired": "请填写密码"})


class StructureForm(forms.ModelForm):
    class Meta:
        model = Structure
        fields = ['type', 'name', 'parent']


class UserCreateForm(forms.ModelForm):
    password = forms.CharField(
        required=True,
        min_length=6,
        max_length=20,
        error_messages={
            "required": "密码不能为空",
            "min_length": "密码长度最少6位数",
        }
    )

    confirm_password = forms.CharField(
        required=True,
        min_length=6,
        max_length=20,
        error_messages={
            "required": "确认密码不能为空",
            "min_length": "密码长度最少6位数",
        }
    )

    class Meta:
        model = User
        fields = [
            'name', 'gender', 'birthday', 'username', 'mobile', 'email',
            'department', 'post', 'superior', 'is_active', 'roles', 'password'
        ]

        error_messages = {
            "name": {"required": "姓名不能为空"},
            "username": {"required": "用户名不能为空"},
            "email": {"required": "邮箱不能为空"},
            "mobile": {
                "required": "手机号码不能为空",
                "max_length": "输入有效的手机号码",
                "min_length": "输入有效的手机号码"
            }
         }

    def clean(self):
        cleaned_data = super(UserCreateForm, self).clean()
        username = cleaned_data.get("username")
        mobile = cleaned_data.get("mobile", "")
        email = cleaned_data.get("email")
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        if User.objects.filter(username=username).count():
            raise forms.ValidationError('用户名：{}已存在'.format(username))

        if password != confirm_password:
            raise forms.ValidationError("两次密码输入不一致")

        if User.objects.filter(mobile=mobile).count():
            raise forms.ValidationError('手机号码：{}已存在'.format(mobile))

        REGEX_MOBILE = "^1[3578]\d{9}$|^147\d{8}$|^176\d{8}$"
        if not re.match(REGEX_MOBILE, mobile):
            raise forms.ValidationError("手机号码非法")

        if User.objects.filter(email=email).count():
            raise forms.ValidationError('邮箱：{}已存在'.format(email))


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            'name', 'gender', 'birthday', 'username', 'mobile', 'email',
            'department', 'post', 'superior', 'is_active', 'roles'
        ]


class PasswordChangeForm(forms.Form):

    password = forms.CharField(
        required=True,
        min_length=6,
        max_length=20,
        error_messages={
            "required": u"密码不能为空"
        })

    confirm_password = forms.CharField(
        required=True,
        min_length=6,
        max_length=20,
        error_messages={
            "required": u"确认密码不能为空"
        })

    def clean(self):
        cleaned_data = super(PasswordChangeForm, self).clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")
        if password != confirm_password:
            raise forms.ValidationError("两次密码输入不一致")


class MenuForm(forms.ModelForm):
    class Meta:
        model = Menu
        fields = '__all__'

apps/system/views.py
from django.views.generic import TemplateView

from .mixin import LoginRequiredMixin
from custom import BreadcrumbMixin


class SystemView(LoginRequiredMixin, BreadcrumbMixin, TemplateView):

    template_name = 'system/system_index.html'

templates/system/menu_list.html
{% extends "base-left.html" %}
{% load staticfiles %}

{% block css %}
    <link rel="stylesheet" href="{% static 'plugins/datatables/jquery.dataTables.min.css' %}">
    <link rel="stylesheet" href="{% static 'js/plugins/layer/skin/layer.css' %}">
    <!-- iCheck for checkboxes and radio inputs -->
{% endblock %}

{% block content %}
    <!-- Main content -->
    <section class="content">
        <div id="devlist">
            <div class="box box-primary" id="liebiao">
                <div class="box-header">
                    <div class="btn-group pull-left">
                        <button type="button" id="btnRefresh" class="btn btn-default">
                            <i class="glyphicon glyphicon-repeat"></i>刷新
                        </button>
                    </div>
                    <div class="btn-group pull-left">&nbsp</div>
                    <div class="btn-group pull-left">
                        <button type="button" id="btnCreate" class="btn btn-default">
                            <i class="glyphicon glyphicon-plus"></i>新增
                        </button>
                    </div>
                </div>
                <div class="box-body">
                    <table id="dtbList" class="display" cellspacing="0" width="100%">
                        <thead>
                        <tr valign="middle">
                            <th><input type="checkbox" id="checkAll"></th>
                            <th>ID</th>
                            <th>名称</th>
                            <th>代码</th>
                            <th>URL</th>
                            <th>图标</th>
                            <th>父菜单</th>
                            <th>操作</th>

                        </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                    <br> <br>
                </div>
            </div>
        </div>
    </section>

    <!-- /.content -->

{% endblock %}

{% block javascripts %}
    <script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'plugins/datatables/dataTables.const.js' %}"></script>
    <script src="{% static 'js/plugins/layer/layer.js' %}"></script>
    <!-- iCheck 1.0.1 -->
    <script type="text/javascript">
        $(function () {
            $('#SYSTEM-RBAC').addClass('active');
            $('#SYSTEM-RBAC-MENU').addClass('active');

        });
    </script>

    <script type="text/javascript">
        var oDataTable = null;
        var data = [
            {% for menu in menu_all %}
            {
                "id": "{{ menu.id }}",
                "name": "{{ menu.name }}",
                "code": "{{ menu.code }}",
                "url":  "{{ menu.url | default_if_none:'' }}",
                "icon": "{{ menu.icon | default_if_none:'' }}",
                "parent": "{{ menu.parent.name }}"
            },
            {% endfor %}
        ];

        $(function () {
            oDataTable = initTable();

            function initTable() {
                var oTable = $('#dtbList').DataTable($.extend(true, {},
                    DATATABLES_CONSTANT.DATA_TABLES.DEFAULT_OPTION,
                    {
                        data: data,
                        columns: [
                            DATATABLES_CONSTANT.DATA_TABLES.COLUMN.CHECKBOX,
                            {
                                data: "id",
                                width: "5%",
                            },
                            {
                                data: "name",
                            },
                            {
                                data: "code",
                            },
                            {
                                data: "url",
                            },
                            {
                                data: "icon",
                            },
                            {
                                data: "parent",
                            },
                            {
                                data: "id",
                                bSortable: "false",
                                render: function (data, type, row, meta) {
                                    var ret = "";
                                    var ret = "<button title='详情-编辑' onclick='doUpdate("
                                        + data + ")'><i class='glyphicon glyphicon-pencil'></i></button>";
                                    return ret;
                                }
                            }
                        ],
                    }));
                return oTable;
            }

        });

    $("#btnRefresh").click(function () {
            window.location.reload();
        });

    $("#btnCreate").click(function () {
        layer.open({
            type: 2,
            title: '新增',
            shadeClose: false,
            maxmin: true,
            area: ['800px', '400px'],
            content: "{% url 'system:rbac-menu-create' %}",
            end: function () {
                //关闭时做的事情
                window.location.reload();
            }
        });
    });

     function doUpdate(id) {
        layer.open({
            type: 2,
            title: '编辑',
            shadeClose: false,
            maxmin: true,
            area: ['800px', '400px'],
            content: ["{% url 'system:rbac-menu-update' %}" + '?id=' + id, 'no'],
            end: function () {
                //关闭时做的事情
                window.location.reload();
            }
        });
    }
    </script>
{% endblock %}

templates/system/role.html
{% extends "base-left.html" %}
{% load staticfiles %}

{% block css %}
    <link rel="stylesheet" href="{% static 'plugins/datatables/jquery.dataTables.min.css' %}">
    <link rel="stylesheet" href="{% static 'js/plugins/layer/skin/layer.css' %}">
{% endblock %}

{% block content %}

    <!-- Main content -->
    <section class="content">
        <div id="devlist">
            <div class="box box-primary" id="liebiao">
                <div class="box-header">
                    <div class="btn-group pull-left">
                        <button type="button" id="btnRefresh" class="btn btn-default">
                            <i class="glyphicon glyphicon-repeat"></i>刷新
                        </button>
                    </div>
                    <div class="btn-group pull-left">&nbsp</div>
                    <div class="btn-group pull-left">
                        <button type="button" id="btnCreate" class="btn btn-default">
                            <i class="glyphicon glyphicon-plus"></i>新增
                        </button>

                    </div>
                    <div class="btn-group pull-left">&nbsp</div>
                    <div class="btn-group pull-left">
                        <button type="button" id="btnDelete" class="btn btn-default">
                            <i class="glyphicon glyphicon-trash"></i>删除
                        </button>
                    </div>
                </div>
                <div class="box-body">
                    <table id="dtbList" class="display" cellspacing="0" width="100%">
                        <thead>
                        <tr valign="middle">
                            <th><input type="checkbox" id="checkAll"></th>
                            <th>ID</th>
                            <th>名称</th>
                            <th>说明</th>
                            <th>操作</th>
                        </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                    <br> <br>
                </div>
            </div>
        </div>
    </section>

    <!-- /.content -->

{% endblock %}

{% block javascripts %}
    <script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'plugins/datatables/dataTables.const.js' %}"></script>
    <script src="{% static 'js/plugins/layer/layer.js' %}"></script>
    <script type="text/javascript">
        $(function () {
            $('#SYSTEM-RBAC').addClass('active');
            $('#SYSTEM-RBAC-ROLE').addClass('active');

        });
    </script>
<script type="text/javascript">
 var oDataTable = null;
    $(function () {
        oDataTable = initTable();

        function initTable() {
            var oTable = $('#dtbList').DataTable($.extend(true, {},
                DATATABLES_CONSTANT.DATA_TABLES.DEFAULT_OPTION,
                {
                    ajax: {
                        "url": "{% url 'system:rbac-role-list' %}",
                    },
                    columns: [
                        DATATABLES_CONSTANT.DATA_TABLES.COLUMN.CHECKBOX,
                        {
                            data: "id",
                            width: "5%",
                        },
                        {
                            data: "name",
                            //width : "20%",
                        },
                        {
                            data: "desc",
                            //width : "20%",
                        },

                        {
                            data: "id",
                            width: "16%",
                            bSortable: "false",
                            render: function (data, type, row, meta) {
                                var ret = "";
                                var ret = "<button title='详情-编辑' onclick='doUpdate("
                                    + data + ")'><i class='glyphicon glyphicon-pencil'></i></button>";
                                ret = ret + "<button title='关联用户' onclick='doUpdateUser("
                                    + data + ")'><i class='glyphicon glyphicon-user'></i></button>";
                                ret = ret + "<button title='关联菜单' onclick='doUpdateMenu("
                                    + data + ")'><i class='glyphicon glyphicon-tree-conifer'></i></button>";
                                ret = ret + "<button title='删除' onclick='doDelete("
                                    + data + ")'><i class='glyphicon glyphicon-trash'></i></button>";
                                return ret;
                            }
                        }],
                    }));
                return oTable;
            }

        });

    $("#btnCreate").click(function () {
        layer.open({
            type: 2,
            title: '新增',
            shadeClose: false,
            maxmin: true,
            area: ['800px', '300px'],
            content: "{% url 'system:rbac-role-create' %}",
            end: function () {
                //关闭时做的事情
                oDataTable.ajax.reload();
            }
        });
    });

    $("#btnRefresh").click(function () {
        oDataTable.ajax.reload();
    });

    function doUpdate(id) {
    layer.open({
        type: 2,
        title: '编辑',
        shadeClose: false,
        maxmin: true,
        area: ['800px', '400px'],
        content: ["{% url 'system:rbac-role-update' %}" + '?id=' + id, 'no'],
        end: function () {
            oDataTable.ajax.reload();
        }
    });
    }

    //checkbox全选
    $("#checkAll").on("click", function () {
        if ($(this).prop("checked") === true) {
            $("input[name='checkList']").prop("checked", $(this).prop("checked"));
            $('#example tbody tr').addClass('selected');
        } else {
            $("input[name='checkList']").prop("checked", false);
            $('#example tbody tr').removeClass('selected');
        }
    });

    //批量删除
    $("#btnDelete").click(function () {
        if ($("input[name='checkList']:checked").length == 0) {
            layer.msg("请选择要删除的记录");
            return;
        }

        var arrId = new Array();
        $("input[name='checkList']:checked").each(function () {
            //alert($(this).val());
            arrId.push($(this).val());
        });

        sId = arrId.join(',');

        layer.alert('确定删除吗？', {
            title: '提示'
            , icon: 3 //0:感叹号 1：对号 2：差号 3：问号 4：小锁 5：哭脸 6：笑脸
            , time: 0 //不自动关闭
            , btn: ['YES', 'NO']
            , yes: function (index) {
                layer.close(index);
                $.ajax({
                    type: "POST",
                    url: "{% url 'system:rbac-role-delete' %}",
                    data: {"id": sId, csrfmiddlewaretoken: '{{ csrf_token }}'},
                    cache: false,
                    success: function (msg) {
                        if (msg.result) {
                            layer.alert("操作成功", {icon: 1});
                            oDataTable.ajax.reload();
                        } else {
                            //alert(msg.message);
                            layer.alert("操作失败", {icon: 2});
                        }
                        return;
                    }
                });
            }
        });
    });

    //删除单个数据
    function doDelete(id) {
        layer.alert('确定删除吗？', {
            title: '提示'
            , icon: 3 //0:感叹号 1：对号 2：差号 3：问号 4：小锁 5：哭脸 6：笑脸
            , time: 0 //不自动关闭
            , btn: ['YES', 'NO']
            , yes: function (index) {
                layer.close(index);
                $.ajax({
                    type: "POST",
                    url: "{% url 'system:rbac-role-delete' %}",
                    data: {"id": id, csrfmiddlewaretoken: '{{ csrf_token }}'},
                    cache: false,
                    success: function (msg) {
                        if (msg.result) {
                            layer.alert('删除成功', {icon: 1});
                            oDataTable.ajax.reload();
                        } else {
                            //alert(msg.message);
                            layer.alert('删除失败', {icon: 2});
                        }
                        return;
                    }
                });
            }
        });
    }

    //关联用户
    function doUpdateUser(id) {
        layer.open({
            type: 2,
            title: '绑定用户',
            shadeClose: false,
            maxmin: true,
            area: ['800px', '600px'],
            content: ["{% url 'system:rbac-role-role2user' %}" + '?id=' + id, 'no'],
        });
    }

    //关联菜单
    function doUpdateMenu(id) {
        layer.open({
            type: 2,
            title: '权限分配',
            shadeClose: false,
            maxmin: true,
            area: ['600px', '480px'],
            content: ["{% url 'system:rbac-role-role2menu' %}" + '?id=' + id, 'no'],

    });
    }
</script>

{% endblock %}

templates/system/role_role2menu.html
{% extends "base-layer.html" %} {% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'plugins/zTree/css/metroStyle/metroStyle.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'plugins/zTree/css/zTreeStyle/zTreeStyle.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'plugins/zTree/css/demo.css' %}" type="text/css">
{% endblock %}
{% block main %}

    <style type="text/css">
        .ztree li span.button.switch.level0 {
            visibility: hidden;
            width: 1px;
        }

        .ztree li ul.level0 {
            padding: 0;
            background: none;
        }


    </style>
    <div class="box box-danger">
        <div class="box-body">
            <form class="form-horizontal" id="addTreeForm" action="" method="post">
                {% csrf_token %}
                <!-- 注释1：页面实例是由Role2MenuView视图返回的，同时传递了上下文role,这里使用role.id时用来提交POST请求时向后台传递的id-->
                <input type="hidden" name='id' value="{{ role.id }}"/>
                <input type="hidden" name="tree" id="tree" value=""/>
                <div class="box-body">
                    <div class="row">
                        <div class="col-xs-5">
                            <div class="row span7 text-center ">
                                <label class="control-label"><h5>所有菜单</h5></label>

                            </div>
                            <div style="zTreeDemoBackground:left">
                                <ul id="left_tree" class="ztree"></ul>
                            </div>
                        </div>
                        <div class="col-xs-2">
                            <br><br><br><br><br><br>
                            <div class="text-center">
                                <button type="button" id="btnSave" class="btn btn-info margin-right ">生成</button>
                            </div>
                            <div class="text-center text-gray margin-top-5">{{ role.name }}权限</div>

                        </div>
                        <div class="col-xs-5">
                            <div class="row span7 text-center">
                                <label class="control-label"><h5>已选菜单</h5></label>
                            </div>
                            <ul id="right_tree" class="ztree"></ul>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    <script type="text/javascript" src="{% static 'plugins/zTree/js/jquery.ztree.core.js' %}"></script>
    <script type="text/javascript" src="{% static 'plugins/zTree/js/jquery.ztree.excheck.js' %}"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            var zTree;
            var demoIframe;

            var left_tree_setting = {
                view: {
                    dblClickExpand: false,
                    showLine: true,
                    selectedMulti: true
                },
                check: {
                    enable: true,
                    //chkboxType : { "Y" : "", "N" : "" }
                },
                data: {
                    key: {
                        name: "name",
                        //title:"title",
                    },
                    simpleData: {
                        enable: true,
                        idKey: "id",
                        pIdKey: "parent",
                        rootPId: ""
                    },
                }
            };

            var right_tree_setting = {
                view: {
                    dblClickExpand: false,
                    showLine: true,
                    selectedMulti: true
                },
                check: {
                    enable: false,
                    //chkboxType : { "Y" : "", "N" : "" }
                },
                data: {
                    key: {
                        name: "name",
                        //title:"title",
                    },
                    simpleData: {
                        enable: true,
                        idKey: "id",
                        pIdKey: "parent",
                        rootPId: ""
                    },
                }
            };

            $.ajax({
                type: "GET",
                url: "{% url 'system:rbac-role-role2menu_list' %}",
                cache: false,
                success: function (msg) {
                    layer.close();
                    var t = $("#left_tree");
                    t = $.fn.zTree.init(t, left_tree_setting, msg.data);
                    var treeObj = $.fn.zTree.getZTreeObj("left_tree");
                    treeObj.expandAll(true);
                    return;
                }
            });

            $.ajax({
                type: "GET",
                url: "{% url 'system:rbac-role-role2menu_list' %}",
                data: {"id":{{role.id}}},
                cache: false,
                success: function (msg) {
                    layer.close();
                    var t = $("#right_tree");
                    t = $.fn.zTree.init(t, right_tree_setting, msg.data);
                    var treeObj = $.fn.zTree.getZTreeObj("right_tree");
                    treeObj.expandAll(true);
                    return;
                }
            });

            $("#btnSave").click(function () {
                var treeObj = $.fn.zTree.getZTreeObj("left_tree");
                var nodes = treeObj.getCheckedNodes(true);
                $("#tree").val(JSON.stringify(nodes));
                var data = $("#addTreeForm").serialize();
                $.ajax({
                    type: $("#addTreeForm").attr('method'),
                    url: "{% url 'system:rbac-role-role2menu' %}",
                    data: data,
                    cache: false,
                    beforeSend: function () {
                        this.layerIndex = layer.load(1, {
                            shade: [0.1, '#fff']
                        });
                    },
                    success: function (msg) {
                        if (msg.result) {
                            layer.alert('操作成功', {icon: 1}, function (index) {
                                parent.layer.closeAll();
                            });
                        } else {
                            //alert(msg.message);
                            layer.alert('操作失败', {icon: 2});
                        }
                        return;
                    }
                });
            });
        });


    </script>
{% endblock %}