apps/cmdb/urls.py
from django.urls import path

from .views import CmdbView
from . import views_code, views_scan, views_eam

app_name = 'cmdb'

urlpatterns = [
    path('', CmdbView.as_view(), name='index'),
    path('portal/code/', views_code.CodeView.as_view(), name='portal-code'),
    path('portal/code/create/', views_code.CodeCreateView.as_view(), name='portal-code-create'),
    path('portal/code/list/', views_code.CodeListView.as_view(), name='portal-code-list'),
    path('portal/code/update/', views_code.CodeUpdateView.as_view(), name='portal-code-update'),
    path('portal/code/delete/', views_code.CodeDeleteView.as_view(), name='portal-code-delete'),

    path('portal/scan_config/', views_scan.ScanConfigView.as_view(), name='portal-scan_config'),
    path('portal/device_scan/', views_scan.DeviceScanView.as_view(), name='portal-device_scan'),
    path('portal/device_scan/list/', views_scan.DeviceScanListView.as_view(), name='portal-device_scan-list'),
    path('portal/device_scan/detail/', views_scan.DeviceScanDetailView.as_view(), name='portal-device_scan-detail'),
    path('portal/device_scan/delete/', views_scan.DeviceScanDeleteView.as_view(), name='portal-device_scan-delete'),
    path('portal/device_scan/exec/', views_scan.DeviceScanExecView.as_view(), name='portal-device_scan-exec'),
    path('portal/device_scan/inbound/', views_scan.DeviceScanInboundView.as_view(), name='portal-device_scan-inbound'),

    path('eam/cabinet/', views_eam.CabinetView.as_view(), name='eam-cabinet'),
    path('eam/cabinet/create/', views_eam.CabinetCreateView.as_view(), name='eam-cabinet-create'),
    path('eam/cabinet/update/', views_eam.CabinetUpdateView.as_view(), name='eam-cabinet-update'),
    path('eam/cabinet/list/', views_eam.CabinetListView.as_view(), name='eam-cabinet-list'),
    path('eam/cabinet/delete/', views_eam.CabinetDeleteView.as_view(), name='eam-cabinet-delete'),

    path('eam/device/', views_eam.DeviceView.as_view(), name='eam-device'),
    path('eam/device/create/', views_eam.DeviceCreateView.as_view(), name='eam-device-create'),
    path('eam/device/update/', views_eam.DeviceUpdateView.as_view(), name='eam-device-update'),
    path('eam/device/list/', views_eam.DeviceListView.as_view(), name='eam-device-list'),
    path('eam/device/delete/', views_eam.DeviceDeleteView.as_view(), name='eam-device-delete'),
    path('eam/device/device2connection/', views_eam.Device2ConnectionView.as_view(), name='eam-device-device2connection'),
    path('eam/device/detail/', views_eam.DeviceDetailView.as_view(), name='eam-device-detail'),
    path('eam/device/upload/', views_eam.DeviceFileUploadView.as_view(), name='eam-device-upload'),
    path('eam/device/file_delete/', views_eam.DeviceFileDeleteView.as_view(), name='eam-device-file_delete'),
    path('eam/device/auto_update_device_info/', views_eam.AutoUpdateDeviceInfo.as_view(),
         name='eam-device-auto_update_device_info'),
]

sandboxMP/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.urls import re_path
from django.views.static import serve

from system.views_user import IndexView, LoginView, LogoutView
from cmdb.tests import TestLoggingView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('system/', include('system.urls', namespace='system')),
    path('cmdb/', include('cmdb.urls', namespace='cmdb')),

    path('test/', TestLoggingView.as_view()),

]

if settings.DEBUG:
    urlpatterns += [
        re_path(r'^media/(?P<path>.*)$', serve, {"document_root": settings.MEDIA_ROOT}),

    ]

apps/cmdb/models.py
from datetime import datetime

from django.db import models
from django.contrib.auth import get_user_model

from simple_history.models import HistoricalRecords

User = get_user_model()


class AbstractMode(models.Model):
    parent = models.ForeignKey(
        'self', blank=True, null=True, on_delete=models.SET_NULL, related_name='child'
    )

    class Meta:
        abstract = True


class Code(AbstractMode):
    key = models.CharField(max_length=80, verbose_name='键')
    value = models.CharField(max_length=80, verbose_name='值')
    desc = models.CharField(max_length=100, blank=True, default='', verbose_name='备注')

    class Meta:
        verbose_name = '字典'
        verbose_name_plural = verbose_name


class TimeAbstract(models.Model):
    add_time = models.DateTimeField(auto_now_add=True, verbose_name="添加时间")
    modify_time = models.DateTimeField(auto_now=True, verbose_name="更新时间")

    class Meta:
        abstract = True


class ConnectionAbstract(models.Model):
    auth_method_choices = (
        ('private_key', '密钥认证'),
        ('password', '密码认证')
    )
    hostname = models.CharField(max_length=50, verbose_name='设备地址(IP或域名)')
    port = models.IntegerField(default=22, verbose_name='SSH端口')
    username = models.CharField(max_length=15, blank=True, default='', verbose_name='SSH用户名')
    password = models.CharField(max_length=80, blank=True, default='', verbose_name='SSH密码')
    private_key = models.CharField(max_length=100, blank=True, default='', verbose_name='密钥路径')
    auth_type = models.CharField(max_length=30, choices=auth_method_choices, default='')
    status = models.CharField(max_length=10, blank=True, default='')

    class Meta:
        abstract = True


class DeviceAbstract(models.Model):
    sys_hostname = models.CharField(max_length=150, blank=True, default='', verbose_name='主机名')
    mac_address = models.CharField(max_length=150, blank=True, default='', verbose_name='MAC地址')
    sn_number = models.CharField(max_length=150, blank=True, default='', verbose_name='SN号码')
    os_type = models.CharField(max_length=150, blank=True, default='', verbose_name='系统类型')
    device_type = models.CharField(max_length=150, blank=True, default='', verbose_name='设备类型')

    class Meta:
        abstract = True


class DeviceScanInfo(ConnectionAbstract, DeviceAbstract, TimeAbstract):
    error_message = models.CharField(max_length=80, blank=True, default='', verbose_name='错误信息')

    class Meta:
        verbose_name = '扫描信息'
        verbose_name_plural = verbose_name


class ConnectionInfo(ConnectionAbstract, TimeAbstract):

    class Meta:
        verbose_name = 'SSH连接信息'
        verbose_name_plural = verbose_name


class Cabinet(models.Model):
    number = models.CharField(max_length=50, verbose_name='机柜编号')
    position = models.CharField(max_length=80, verbose_name='机柜位置')
    desc = models.TextField(blank=True, default='', verbose_name='备注信息')

    class Meta:
        verbose_name = '机柜信息'
        verbose_name_plural = verbose_name


class DeviceInfo(AbstractMode, DeviceAbstract, TimeAbstract):
    hostname = models.CharField(max_length=50, verbose_name='设备地址(IP或域名)')
    network_type = models.IntegerField(blank=True, null=True, verbose_name='网络类型')
    service_type = models.IntegerField(blank=True, null=True, verbose_name='服务类型')
    operation_type = models.IntegerField(blank=True, null=True, verbose_name='业务类型')
    leader = models.IntegerField(blank=True, null=True, verbose_name='责任人')
    dev_cabinet = models.IntegerField(blank=True, null=True, verbose_name='机柜信息')
    dev_connection = models.IntegerField(blank=True, null=True, verbose_name='连接信息')
    buyDate = models.DateField(default=datetime.now, verbose_name="购买日期")
    warrantyDate = models.DateField(default=datetime.now, verbose_name="到保日期")
    desc = models.TextField(blank=True, default='', verbose_name='备注信息')
    changed_by = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL)
    history = HistoricalRecords(excluded_fields=['add_time', 'modify_time', 'parent'])

    class Meta:
        verbose_name = '设备信息'
        verbose_name_plural = verbose_name

    @property
    def _history_user(self):
        return self.changed_by

    @_history_user.setter
    def _history_user(self, value):
        self.changed_by = value


class DeviceFile(TimeAbstract):
    device = models.ForeignKey('DeviceInfo', blank=True, null=True, on_delete=models.SET_NULL, verbose_name='设备')
    file_content = models.FileField(upload_to="asset_file/%Y/%m", null=True, blank=True, verbose_name="资产文件")
    upload_user = models.CharField(max_length=20, verbose_name="上传人")

apps/cmdb/forms.py
# @Time   : 2018/12/19 16:13
# @Author : RobbieHan
# @File   : forms.py

from django import forms

from .models import Code, DeviceInfo, ConnectionInfo, DeviceFile


class CodeCreateForm(forms.ModelForm):
    class Meta:
        model = Code
        fields = '__all__'

        error_messages = {
            'key': {'required': 'key不能为空'},
            'value': {'required': 'value不能为空'}
        }

    def clean(self):
        cleaned_data = super(CodeCreateForm, self).clean()
        key = cleaned_data.get('key')
        value = cleaned_data.get('value')

        if Code.objects.filter(key=key).count():
            raise forms.ValidationError('key：{}已存在'.format(key))

        if Code.objects.filter(value=value).count():
            raise forms.ValidationError('value: {}已存在'.format(value))


class CodeUpdateForm(CodeCreateForm):

    def clean(self):
        cleaned_data = self.cleaned_data
        key = cleaned_data.get('key')
        value = cleaned_data.get('value')

        if self.instance:
            matching_code = Code.objects.exclude(pk=self.instance.pk)
            if matching_code.filter(key=key).exists():
                msg = 'key：{} 已经存在'.format(key)
                raise forms.ValidationError(msg)
            if matching_code.filter(value=value).exists():
                msg = 'value：{} 已经存在'.format(value)
                raise forms.ValidationError(msg)


class DeviceCreateForm(forms.ModelForm):
    class Meta:
        model = DeviceInfo
        exclude = ['dev_connection']
        error_messages = {
            'hostname': {'required': '请填写设备地址'},
            'buyDate': {'required': '请填写购买日期'},
            'warrantyDate': {'required': '请填写到保日期'}
        }

    def clean(self):
        cleaned_data = super(DeviceCreateForm, self).clean()
        hostname = cleaned_data.get('hostname')

        if DeviceInfo.objects.filter(hostname=hostname).count():
            raise forms.ValidationError('设备地址：{}已存在'.format(hostname))


class DeviceUpdateForm(DeviceCreateForm):
    def clean(self):
        cleaned_data = self.cleaned_data
        hostname = cleaned_data.get('hostname')

        if self.instance:
            matching_device = DeviceInfo.objects.exclude(pk=self.instance.pk)
            if matching_device.filter(hostname=hostname).exists():
                raise forms.ValidationError('设备地址：{}已存在'.format(hostname))


class ConnectionInfoForm(forms.ModelForm):

    class Meta:
        model = ConnectionInfo
        fields = '__all__'

        error_messages = {
            'port': {'required': '端口不能为空'},
        }

    def clean(self):
        cleaned_data = self.cleaned_data
        username = cleaned_data.get('username')
        password = cleaned_data.get('password')
        private_key = cleaned_data.get('private_key')
        auth_type = cleaned_data.get('auth_type')
        if len(username) == 0:
            raise forms.ValidationError('用户名不能为空！')
        if auth_type == 'password' and len(password) == 0:
            raise forms.ValidationError('认证类型为[密码]时，必须设置密码信息！')
        if auth_type == 'private_key' and len(private_key) == 0:
            raise forms.ValidationError('认证类型为[密钥]时，必须设置密钥信息！')


class DeviceFileUploadForm(forms.ModelForm):
    class Meta:
        model = DeviceFile
        fields = '__all__'

apps/cmdb/views.py
from django.views.generic import TemplateView

from system.mixin import LoginRequiredMixin
from custom import BreadcrumbMixin


class CmdbView(LoginRequiredMixin, BreadcrumbMixin, TemplateView):

    template_name = 'cmdb/cmdb_index.html'

templates/cmdb/cabinet_form.html
{% extends 'base-layer.html' %}
{% load staticfiles %}
{% block css %}
    <link rel="stylesheet" href="{% static 'plugins/select2/select2.min.css' %}">
    <!-- iCheck for checkboxes and radio inputs -->
{% endblock %}
{% block main %}
    <div class="box box-danger">
        <form class="form-horizontal" id="addForm" method="post">
            <input type="hidden" name='id' value="{{ cabinet.id }}" />
            {% csrf_token %}
            <div class="box-body">
                <fieldset>
                    <legend>
                        <h4>机柜信息</h4>
                    </legend>

                    <div class="form-group has-feedback">
                        <label class="col-sm-2 control-label">机柜编号</label>
                        <div class="col-sm-3">
                            <input class="form-control" name="number" type="text" value="{{ cabinet.number }}"/>
                        </div>
                        <label class="col-sm-2 control-label">机柜位置</label>
                        <div class="col-sm-3">
                            <input class="form-control" name="position" type="text" value="{{ cabinet.position }}"/>
                        </div>

                    </div>

                    <div class="form-group has-feedback">
                        <label class="col-sm-2 control-label">描述信息</label>
                        <div class="col-sm-8">
                            <input class="form-control" id="desc" name="desc" type="text" value="{{ cabinet.desc }}"/>
                        </div>
                    </div>

                </fieldset>
            </div>
            <div class="box-footer ">
                <div class="row span7 text-center ">
                    <button type="button" id="btnCancel" class="btn btn-default margin-right ">重置</button>
                    <button type="button" id="btnSave" class="btn btn-info margin-right ">保存</button>
                </div>
            </div>

        </form>
    </div>

{% endblock %}

{% block javascripts %}
    <script src="{% static 'plugins/select2/select2.full.min.js' %}"></script>
    <script type="text/javascript">

    function getUrl() {
            if ($("input[name='id']").val()) {
                var url = "{% url 'cmdb:eam-cabinet-update' %}";
            } else {
                var url = "{% url 'cmdb:eam-cabinet-create' %}";
            }
            return url
        }

    $("#btnSave").click(function () {
        var data = $("#addForm").serialize();
        $.ajax({
            type: $("#addForm").attr('method'),
            url: getUrl(),
            data: data,
            cache: false,
            success: function (msg) {
                if (msg.result) {
                    layer.alert('数据保存成功！', {icon: 1}, function (index) {
                        parent.layer.closeAll(); //关闭所有弹窗
                    });
                } else {
                    layer.alert(msg.error, {icon: 5});
                    //$('errorMessage').html(msg.message)
                }
                return;
            }
        });
    });


        /*点取消刷新新页面*/
        $("#btnCancel").click(function () {
            window.location.reload();

        });

        $(function () {
            //Initialize Select2 Elements
            $(".select2").select2();
        });

    </script>

{% endblock %}

templates/cmdb/code_create.html
{% extends 'base-layer.html' %}
{% load staticfiles %}
{% block css %}
    <link rel="stylesheet" href="{% static 'plugins/select2/select2.min.css' %}">
    <!-- iCheck for checkboxes and radio inputs -->
{% endblock %}
{% block main %}
    <div class="box box-danger">
        <form class="form-horizontal" id="addForm" method="post">
            {% csrf_token %}
            <div class="box-body">
                <fieldset>
                    <legend>
                        <h4>新建字典</h4>
                    </legend>

                    <div class="form-group has-feedback">
                        <label class="col-sm-2 control-label">KEY</label>
                        <div class="col-sm-3">
                            <input class="form-control" name="key" type="text"/>
                        </div>
                        <label class="col-sm-2 control-label">VALUE</label>
                        <div class="col-sm-3">
                            <input class="form-control" name="value" type="text" />
                        </div>

                    </div>

                    <div class="form-group has-feedback">
                        <label class="col-sm-2 control-label">父菜单</label>
                        <div class="col-sm-3">
                            <select class="form-control select2" name="parent">
                                <option value=""></option>
                                {% for parent in code_parent %}
                                    <option value={{ parent.id }}> {{ parent.value }} </option>
                                {% endfor %}
                            </select>
                        </div>
                        <label class="col-sm-2 control-label">描述信息</label>
                        <div class="col-sm-3">
                            <input class="form-control" id="desc" name="desc" type="text" />
                        </div>
                    </div>

                </fieldset>
            </div>
            <div class="box-footer ">
                <div class="row span7 text-center ">
                    <button type="button" id="btnCancel" class="btn btn-default margin-right ">重置</button>
                    <button type="button" id="btnSave" class="btn btn-info margin-right ">保存</button>
                </div>
            </div>

        </form>
    </div>

{% endblock %}

{% block javascripts %}
    <script src="{% static 'plugins/select2/select2.full.min.js' %}"></script>
    <script type="text/javascript">
    $("#btnSave").click(function () {
        var data = $("#addForm").serialize();
        $.ajax({
            type: $("#addForm").attr('method'),
            url: "{% url 'cmdb:portal-code-create' %}",
            data: data,
            cache: false,
            success: function (msg) {
                if (msg.result) {
                    layer.alert('数据保存成功！', {icon: 1}, function (index) {
                        parent.layer.closeAll(); //关闭所有弹窗
                    });
                } else {
                    layer.alert(msg.error, {icon: 5});
                    //$('errorMessage').html(msg.message)
                }
                return;
            }
        });
    });


        /*点取消刷新新页面*/
        $("#btnCancel").click(function () {
            window.location.reload();

        });

        $(function () {
            //Initialize Select2 Elements
            $(".select2").select2();
        });

    </script>

{% endblock %}

templates/cmdb/deviceinfo.html
{% extends "base-left.html" %}
{% load staticfiles %}

{% block css %}
    <link rel="stylesheet" href="{% static 'plugins/datatables/jquery.dataTables.min.css' %}">
    <link rel="stylesheet" href="{% static 'js/plugins/layer/skin/layer.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/select2/select2.min.css' %}">
{% endblock %}

{% block content %}

    <!-- Main content -->
  <section class="content">
    <div id="devlist">
        <div class="box box-primary" id="liebiao">
            <div class="box-header">
                <div class="btn-group pull-left">
                    <button type="button" id="btnRefresh" class="btn btn-default">
                        <i class="glyphicon glyphicon-repeat"></i>刷新
                    </button>
                </div>
                <div class="btn-group pull-left">&nbsp</div>
                <div class="btn-group pull-left">
                    <button type="button" id="btnCreate" class="btn btn-default">
                        <i class="glyphicon glyphicon-plus"></i>新增
                    </button>

                </div>
                <div class="btn-group pull-left">&nbsp</div>
                <div class="btn-group pull-left">
                    <button type="button" id="btnDelete" class="btn btn-default">
                        <i class="glyphicon glyphicon-trash"></i>删除
                    </button>
                </div>
            </div>
            <div class="box-header">
                <form class="form-inline" id="queryForm">
                    <div class="form-group searchArea margin-r-5 margin-top-5">
                        <label>主机名：</label>
                        <input type="text" name="sys_hostname" class="form-control inputText" id="sys_hostname">
                    </div>
                    <div class="form-group searchArea margin-r-5 margin-top-5">
                        <label>设备地址：</label>
                        <input type="text" name="hostname" class="form-control inputText" id="hostname">
                    </div>
                    <div class="form-group searchArea margin-r-5 margin-top-5">
                        <label>网络类型：</label>
                        <select class="form-control inputText select2" name="network_type" id="network_type">
                          <option></option>
                          {% for code in all_code %}
                              {% ifequal code.parent.key 'NETWORK_TYPE' %}
                                <option value="{{ code.id }}">{{ code.value }}</option>
                              {% endifequal %}
                          {% endfor %}
                         </select>
                    </div>
                    <div class="form-group searchArea margin-r-5 margin-top-5">
                        <label>服务类型：</label>
                        <select class="form-control inputText select2" name="service_type" , id="service_type">
                          <option></option>
                          {% for code in all_code %}
                              {% if code.parent.key == 'SERVICE_TYPE' %}
                                <option value="{{ code.id }}">{{ code.value }}</option>
                              {% endif %}
                          {% endfor %}
                        </select>
                    </div>
                    <div class="form-group searchArea margin-r-5 margin-top-5">
                        <label>业务类型：</label>
                        <select class="form-control inputText select2" name="operation_type" , id="operation_type">
                          <option></option>
                          {% for code in all_code %}
                              {% if code.parent.key == 'OPERATION_TYPE' %}
                                <option value="{{ code.id }}">{{ code.value }}</option>
                              {% endif %}
                          {% endfor %}
                        </select>
                    </div>
                  <button type="button" id="btnSearch" class="btn btn-default">
                    <i class="glyphicon glyphicon-search"></i>查询
                  </button>
                </form>
            </div>

            <div class="box-body">
                <table id="dtbList" class="display" cellspacing="0" width="100%">
                    <thead>
                    <tr valign="middle">
                        <th><input type="checkbox" id="checkAll"></th>
                        <th>ID</th>
                        <th>主机名</th>
                        <th>SN编号</th>
                        <th>系统类型</th>
                        <th>设备类型</th>
                        <th>设备地址</th>
                        <th>MAC地址</th>
                        <th>责任人</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
                <br> <br>
            </div>
        </div>
    </div>

  </section>

    <!-- /.content -->

{% endblock %}


{% block javascripts %}

<script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'plugins/datatables/dataTables.const-1.js' %}"></script>
<script src="{% static 'js/plugins/layer/layer.js' %}"></script>
<script src="{% static 'plugins/select2/select2.full.min.js' %}"></script>

<script type="text/javascript">
    // 菜单选中高亮
    $(function () {
        $('#CMDB-EAM').addClass('active');
        $('#CMDB-EAM-DEVICE').addClass('active');

    });

    // datatables 初始化配置
    var oDataTable = null;
    $(function () {
        oDataTable = initTable();

        function initTable() {
            var oTable = $('#dtbList').DataTable($.extend(true, {},
                DATATABLES_CONSTANT.DATA_TABLES.SERVER_SIDE_OPTION,

                {
                    ajax: {
                        "url": "{% url 'cmdb:eam-device-list' %}",
                        "data": function (d) {
                                d.sys_hostname = $("#sys_hostname").val();
                                d.hostname = $("#hostname").val();
                                d.network_type = $("#network_type").val();
                                d.service_type = $("#service_type").val();
                                d.operation_type = $("#operation_type").val();
                            }
                    },
                    columns: [
                        DATATABLES_CONSTANT.DATA_TABLES.COLUMN.CHECKBOX,

                        {
                            data: "id",
                        },
                        {
                            data: "sys_hostname",
                        },
                        {
                            data: "sn_number",
                        },
                        {
                            data: "os_type",
                        },
                        {
                            data: "device_type",
                        },
                        {
                            data: "hostname",
                        },
                        {
                            data: "mac_address",
                        },
                        {
                            data: "leader",
                        },
                        {
                            data: "id",
                            bSortable: "false",
                            render: function (data, type, row, meta) {
                                var ret = "<button title='详情' onclick='doDetail("
                                    + data + ")'><i class='glyphicon glyphicon-list-alt'></i></button>";
                                ret = ret + "<button title='修改' onclick='doUpdate("
                                    + data + ")'><i class='glyphicon glyphicon-pencil'></i></button>";
                                ret = ret + "<button title='认证管理' onclick='doDevice2Connection("
                                    + data + ")'><i class='glyphicon glyphicon-user'></i></button>";
                                ret = ret + "<button title='删除' onclick='doDelete("
                                    + data + ")'><i class='glyphicon glyphicon-trash'></i></button>";
                                return ret;
                            }
                        }],
                    }));
                return oTable;
            }

        });

    // 刷新数据
    $("#btnRefresh").click(function () {
        window.location.reload();
    });
    //新建数据
    $("#btnCreate").click(function () {
        var div=layer.open({
            type: 2,
            title: '新增',
            shadeClose: false,
            maxmin: true,
            area: ['800px', '400px'],
            content: "{% url 'cmdb:eam-device-create' %}",
            end: function () {
                //关闭时做的事情
                oDataTable.ajax.reload();
            }
        });
        layer.full(div )
    });

    //修改数据
    function doUpdate(id) {
        var div=layer.open({
            type: 2,
            title: '编辑',
            shadeClose: false,
            maxmin: true,
            area: ['800px', '400px'],
            content: ["{% url 'cmdb:eam-device-update' %}" + '?id=' + id, 'no'],
            end: function () {
                oDataTable.ajax.reload();
            }
        });
        layer.full(div )
    }

    //checkbox全选
    $("#checkAll").on("click", function () {
        if ($(this).prop("checked") === true) {
            $("input[name='checkList']").prop("checked", $(this).prop("checked"));
            $('#example tbody tr').addClass('selected');
        } else {
            $("input[name='checkList']").prop("checked", false);
            $('#example tbody tr').removeClass('selected');
        }
    });

    //批量删除
    $("#btnDelete").click(function () {
        if ($("input[name='checkList']:checked").length == 0) {
            layer.msg("请选择要删除的记录");
            return;
        }

        var arrId = new Array();
        $("input[name='checkList']:checked").each(function () {
            //alert($(this).val());
            arrId.push($(this).val());
        });

        sId = arrId.join(',');

        layer.alert('确定删除吗？', {
            title: '提示'
            , icon: 3 //0:感叹号 1：对号 2：差号 3：问号 4：小锁 5：哭脸 6：笑脸
            , time: 0 //不自动关闭
            , btn: ['YES', 'NO']
            , yes: function (index) {
                layer.close(index);
                $.ajax({
                    type: "POST",
                    url: "{% url 'cmdb:eam-device-delete' %}",
                    data: {"id": sId, csrfmiddlewaretoken: '{{ csrf_token }}'},
                    cache: false,
                    success: function (msg) {
                        if (msg.result) {
                            layer.alert("操作成功", {icon: 1});
                            oDataTable.ajax.reload();
                        } else {
                            //alert(msg.message);
                            layer.alert("操作失败", {icon: 2});
                        }
                        return;
                    }
                });
            }
        });
    });

    //删除单个数据
    function doDelete(id) {
        layer.alert('确定删除吗？', {
            title: '提示'
            , icon: 3 //0:感叹号 1：对号 2：差号 3：问号 4：小锁 5：哭脸 6：笑脸
            , time: 0 //不自动关闭
            , btn: ['YES', 'NO']
            , yes: function (index) {
                layer.close(index);
                $.ajax({
                    type: "POST",
                    url: "{% url 'cmdb:eam-device-delete' %}",
                    data: {"id": id, csrfmiddlewaretoken: '{{ csrf_token }}'},
                    cache: false,
                    success: function (msg) {
                        if (msg.result) {
                            layer.alert('删除成功', {icon: 1});
                            oDataTable.ajax.reload();
                        } else {
                            //alert(msg.message);
                            layer.alert('删除失败', {icon: 2});
                        }
                        return;
                    }
                });
            }
        });
    }

    //select2
    $(function () {
        //Initialize Select2 Elements
        $(".select2").select2();
    });

    $("#btnSearch").click(function(){
        oDataTable.ajax.reload();
    });


    function doDevice2Connection(id) {
          layer.open({
            type: 2,
            title: '认证管理',
            shadeClose: false,
            maxmin: true,
            area: ['800px', '400px'],
            content: ["{% url 'cmdb:eam-device-device2connection' %}" + '?id=' + id, 'no'],
            end: function () {
                oDataTable.ajax.reload();
            }
        });
        }

    function doDetail(id){
        window.location.href="{% url 'cmdb:eam-device-detail' %}?id="+id;
    }
</script>
{% endblock %}